### ISSUE TITLE
Very - Very _ Very nice and many THANKSSSSSSSs !!!

### ISSUE THREAD

**Issue by fanisatt** [faytor/moon_phase_calculator#1]
I shall use your code (inside an application I have done) ! 
https://sourceforge.net/projects/eortologio-gr/
C code : https://github.com/fanisatt/EORTOLOGIO-GR/releases/tag/EORTOLOGIO
It is a free application (Diary) only for Greeks...
I'm in the testing phase now for my next version in which there will be astronomical data.
For the sunrise - sunset I used a famous free program !!!!
See ...  Roger W. Sinnott  !!!!
He wrote it in Basic and I made a C "translation".... 
Your code will cover the phases of the moon.
I have made a very small intervention... You will understand :
.....
    elong = round(elong);
    double temp = ((elong + 6.43) / 360.0) * 28.0;
    **double temp1 = modf(temp,&jd);**
    moonNum = (int) jd ;
   
    if (moonNum >= 28 )
    {
      moonNum = 0;
    }
    
    switch (moonNum) {
    
    case 0 : 
        **if (temp1 > (double) 0.90)** strcpy (MoonStr , "New Moon (+)");
        else strcpy (MoonStr , "New Moon");
        break ;
        
    case 14:
        if (temp1 > (double) 0.90) strcpy (MoonStr , "Full Moon (+)");
        else strcpy (MoonStr , "Full Moon");
        break;
            
    default :
        
        if (temp1 > (double) 0.90) sprintf (MoonStr , "%2d days(+) Moon",moonNum) ;
        else sprintf (MoonStr , "%2d days Moon",moonNum) ; 
    }

See the video please... : https://youtu.be/QFaukkt8xfU
I need your name to mention you officially when the new version will be ready. ( I have some other things to upgrade...regardless of astronomical data ! )
To the moment I search for a good C Code  to calculate the MoonRise and MoonSet...
Many Thanks.
My email : fanisatt@yahoo.gr

**Comment by faytor** [comment]
Hi @fanisatt ,
Thank you for you kind comment. I'm happy to see that this program was useful for you.
If you want, you can just mention TorLab with a link to this repository.
Cheers,

**Comment by fanisatt** [comment]
Your welcome my friend !!As you wish...(I have already discovered a (sky-telescope) basic programm to calculate the moonrise - moonset and I make a corresponding C function from this in order to support fully my application)Best Regards !!

    Στις Δευτέρα 21 Φεβρουαρίου 2022, 09:58:55 μ.μ. EET, ο χρήστης TorLAB ***@***.***> έγραψε:  
 
 


Hi @fanisatt ,
Thank you for you kind comment. I'm happy to see that this program was useful for you.
If you want, you can just mention TorLab with a link this repository.
Cheers,

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fanisatt** [comment]
Your welcome my friend !!
As you wish...
(I have already discovered a (sky-telescope) basic programm to calculate the moonrise - moonset and I make a corresponding C function from this in order to support fully my application)
Best Regards !!

**Comment by faytor** [comment]
Thanks
